apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deployment
  labels:
    app: login-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-deployment
  template:
    metadata:
      labels:
        app: login-deployment
    spec:
      containers:
      - name: login-deployment
        image: docker.io/sanketrokade/login:latest
        ports:
        - containerPort: 5000

