apiVersion: v1
kind: Service
metadata:
  name: login-deployment
spec:
  type: NodePort
  selector:
    app: login-deployment
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
      
